spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tale?useUnicode=true&useSSL=false&characterEncoding=utf8?serverTimezone=Asia/Shanghai
server:
  port: 8500
  tomcat.uri-encoding: UTF-8
  servlet:
    session:
      timeout: 30
  error:
    path: /error

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # ?????????sql?????????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.yzq.talespring.model